### ISSUE TITLE
PHP 8.1 incompatibility

### ISSUE THREAD

**Issue by pacmanito** [littlebizzy/speed-demon#4]
Hi and thank you for your hard work and bringing the plugin to the masses.
Unfortunately as is the plugin crashes WP installation on PHP 8.1, here's what is thrown into the log:
```
PHP Fatal error:  Uncaught Error: Call to undefined method LittleBizzy\SpeedDemon\Core\Core::queryVar() in \wp-content\plugins\speed-demon\modules\disable-embeds\embeds\hooks.php:61
Stack trace:
#0 \wp-includes\class-wp-hook.php(307): LittleBizzy\SpeedDemon\Modules\Disable_Embeds\Embeds\Hooks->init('')
#1 \wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 \wp-includes\plugin.php(476): WP_Hook->do_action(Array)
#3 \wp-settings.php(598): do_action('init')
#4 \wp-config.php(98): require_once('C:\\Programs\\lar...')
#5 \wp-load.php(50): require_once('C:\\Programs\\lar...')
#6 \wp-admin\admin.php(34): require_once('C:\\Programs\\lar...')
#7 \wp-admin\index.php(10): require_once('C:\\Programs\\lar...')
#8 {main}
  thrown in \wp-content\plugins\speed-demon\modules\disable-embeds\embeds\hooks.php on line 61
```

**Comment by jessuppi** [comment]
Thanks for reporting @pacmanito 

We are actually rewriting the entire plugin into a more standard structure, so stay tuned.

**Comment by pacmanito** [comment]
I am sorry to bother but is there any progress? I really like your plugin compared to bloated "optimizer" plugins from WP repo but it's really time to update to PHP 8.1 for me as PHP 8.0 is nearing it's end of support.

**Comment by jessuppi** [comment]
We are mostly focused on our SlickStack script and free HoverCraft theme for WordPress lately, I'm not sure how many of our plugins we will prioritize in the future.

**Comment by pacmanito** [comment]
I see you've been putting a lot of effort into updating your plugins lately, including some of those that are part of the Speed ​​Daemon. Is there any hope that the whole bundle will become compatible with modern PHP in the foreseeable future?

**Comment by jessuppi** [comment]
Sure @pacmanito 

If you are willing to leave LittleBizzy an honest review on Capterra or SourceForge it would encourage us too!
